### ISSUE TITLE
Compatibility with paper 1.19.2

### ISSUE THREAD

**Issue by javipas** [flokol120/Spigot-Item-Chest-Sorter#42]
Hello, i have a minecraft server with some friends with paper 1.19.2 and we are having problems using your plug-in.
Any news about the compatibility?

**Comment by flokol120** [comment]
I did not test 1.19.2 yet. I will try to take a look into it by the end of the week.

**Comment by flokol120** [comment]
@javipas 
Sorry had more work than anticipated. I can confirm that 1.19.2 is not working for me either.

**But there is a temporary work-around: Disable the animations in the config.yml**

```yml
...
# animation configuration
animation:
  # If true items are being animated. If false no animation will be drawn
  enabled: false
...
```
